site_name: Delfenite Artifacts
site_author: Freeze Dolphin

repo_url: https://github.com/freeze-dolphin/docs
remote_branch: gh-pages

theme: 
   name: material
   locale: en
   highlightjs: true

markdown_extensions:
   - smarty: {}
   - toc:
        permalink: True
   - sane_lists: {}
   
plugins: 
   - search
