name: Build & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate MkDocs
        run: |
          sudo pip install mkdocs mkdocs-material
          sudo mkdocs build
          tree .

#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          branch: gh-pages
#          folder: ./PVPINBlocklyEditor/dist/
